- hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: Install JDK 1.8
      shell: "yum install -y java-1.8.0-openjdk"
      register: jdk_install_result

    - name: Display JDK version
      shell: java -version 2>&1
      register: display_java_version
